package scan

import (
	"strings"

	"github.com/pyneda/sukyan/pkg/passive"
)

type Platform string

const (
	PlatformJava Platform = "java"
	PlatformPhp  Platform = "php"
	PlatformNode Platform = "node"
)

func ParsePlatform(platform string) Platform {
	switch strings.ToLower(platform) {
	case "java":
		return PlatformJava
	case "php":
		return PlatformPhp
	case "node":
		return PlatformNode
	default:
		return ""
	}
}

func (p Platform) String() string {
	return string(p)
}

func (p Platform) MatchesAnyFingerprint(fingerprints []passive.Fingerprint) bool {
	if len(fingerprints) == 0 {
		return false
	}
	for _, fingerprint := range fingerprints {
		for _, software := range SoftwareList(p) {
			if strings.EqualFold(fingerprint.Name, software) {
				return true
			} else if strings.EqualFold(string(p), software) {
				return true
			}
		}
	}
	return false

}

func SoftwareList(platform Platform) []string {
	switch platform {
	case PlatformJava:
		return JavaSoftwareList()
	case PlatformPhp:
		return PhpSoftwareList()
	case PlatformNode:
		return NodeSoftwareList()
	default:
		return []string{}
	}
}

func JavaSoftwareList() []string {
	return []string{
		"Adobe Experience Manager",
		"Ametys",
		"Apache Tomcat",
		"Apache Wicket",
		"Apereo CAS",
		"Atlassian Confluence",
		"Atlassian Jira",
		"Blade",
		"Brightspot",
		"Ckan",
		"Contensis",
		"DM Polopoly",
		"Gerrit",
		"Gitiles",
		"GlassFish",
		"Google Web Toolkit",
		"HCL Commerce",
		"HCL Digital Experience",
		"HCL Domino",
		"Halo",
		"JAlbum",
		"Java Servlet",
		"JavaServer Faces",
		"JavaServer Pages",
		"Jenkins",
		"Jetty",
		"K-Sup",
		"Liferay",
		"Lucene",
		"Open-Xchange App Suite",
		"OpenCms",
		"OpenGSE",
		"OpenGrok",
		"Oracle WebLogic Server",
		"Public CMS",
		"Resin",
		"SAP Commerce Cloud",
		"Skolengo",
		"SonarQubes",
		"Spring",
		"TeamCity",
		"Vaadin",
		"ZK",
		"Zimbra",
		"pirobase CMS",
		"uPortal",
	}
}

func PhpSoftwareList() []string {
	return []string{
		"1C-Bitrix",
		"AbhiCMS",
		"Adminer",
		"Aegea",
		"Aksara CMS",
		"AlvandCMS",
		"Amiro.CMS",
		"Apereo CAS",
		"Arastta",
		"BIGACE",
		"Backdrop",
		"Banshee",
		"Batflat",
		"BigTree CMS",
		"Bigware",
		"BoidCMS",
		"Bolt CMS",
		"BookStack",
		"Brownie",
		"CMS Made Simple",
		"CMSimple",
		"CPG Dragonfly",
		"CS Cart",
		"Cachet",
		"CakePHP",
		"Cargo",
		"Centminmod",
		"Chamilo",
		"Chevereto",
		"Classeh",
		"ClickHeat",
		"Clockwork",
		"Cloudify.store",
		"Cloudrexx",
		"CodeIgniter",
		"Concrete CMS",
		"Contao",
		"Contenido",
		"Convertr",
		"Coppermine",
		"Cotonti",
		"CubeCart",
		"Danneo CMS",
		"DataLife Engine",
		"DedeCMS",
		"DirectAdmin",
		"Discuz! X",
		"Dokeos",
		"DokuWiki",
		"Dotclear",
		"Dotser",
		"Drupal",
		"EC-CUBE",
		"Ebasnet",
		"ElasticSuite",
		"Elcodi",
		"Eleanor CMS",
		"Eticex",
		"Eveve",
		"ExpressionEngine",
		"FUDforum",
		"Fat-Free Framework",
		"Flarum",
		"FluxBB",
		"Flyspray",
		"GLPI",
		"Gambio",
		"GetSimple CMS",
		"Gnuboard",
		"Grav",
		"Hamechio",
		"HeliumWeb",
		"Hotaru CMS",
		"Huberway",
		"IPB",
		"Ibexa DXP ",
		"ImpressCMS",
		"ImpressPages",
		"Indexhibit",
		"InstantCMS",
		"JobberBase",
		"Joomla",
		"KPHP",
		"Kitcart",
		"Koala Framework",
		"Kohana",
		"Koken",
		"Komodo CMS",
		"Kooomo",
		"LEPTON",
		"Laravel",
		"LightMon Engine",
		"Lithium",
		"LiveStreet CMS",
		"MODX",
		"Magento",
		"MaxSite CMS",
		"MaxenceDEVCMS",
		"MediaWiki",
		"Melis Platform",
		"Moguta.CMS",
		"Moodle",
		"MotoCMS",
		"MyBB",
		"Neos Flow",
		"Nette Framework",
		"Nextcloud",
		"NexusPHP",
		"OXID eShop",
		"OXID eShop Community Edition",
		"OXID eShop Enterprise Edition",
		"OXID eShop Professional Edition",
		"Omurga Sistemi",
		"OnShop",
		"Open Journal Systems",
		"Open eShop",
		"OpenCart",
		"OpenElement",
		"OpenSwoole",
		"OroCommerce",
		"PHP-Nuke",
		"PHPFusion",
		"Pantheon",
		"Paymenter",
		"Phabricator",
		"PhotoShelter",
		"Pimcore",
		"Pingoteam",
		"PrestaShop",
		"ProcessWire",
		"Proximis Unified Commerce",
		"Pterodactyl Panel",
		"Question2Answer",
		"RBS Change",
		"REDAXO",
		"RainLoop",
		"RiteCMS",
		"RoadRunner",
		"Roadiz CMS",
		"RoundCube",
		"Rubedo",
		"SPIP",
		"SQL Buddy",
		"Saly",
		"Sapren",
		"Seko OmniReturns",
		"Selldone",
		"Serendipity",
		"Shopery",
		"Shoptet",
		"Shopware",
		"Shuttle",
		"Silverstripe",
		"Simple Machines Forum",
		"SimpleSAMLphp",
		"SitePad",
		"Skilldo",
		"Sky-Shop",
		"Solodev",
		"SoteShop",
		"SpiritShop",
		"SquirrelMail",
		"Squiz Matrix",
		"Statamic",
		"Subrion",
		"SummerCart",
		"Symfony",
		"TYPO3 CMS",
		"Tebex",
		"Textpattern CMS",
		"Thelia",
		"ThinkPHP",
		"TwistPHP",
		"Typecho",
		"UMI.CMS",
		"Ultimate Bulletin Board",
		"Upvoty",
		"Ushahidi",
		"Uvodo",
		"Vanilla",
		"Visual Composer",
		"Webasyst Shop-Script",
		"Weblication",
		"Website Creator",
		"WebsiteBaker",
		"Weebly",
		"Wolf CMS",
		"Woltlab Community Framework",
		"WordPress",
		"X-Cart",
		"XAMPP",
		"XOOPS",
		"XenForo",
		"Yii",
		"Yoori",
		"YouCan",
		"Zabbix",
		"Zoey",
		"Zozo",
		"a-blog cms",
		"e107",
		"eSyndiCat",
		"eZ Publish",
		"experiencedCMS",
		"gitlist",
		"h5ai",
		"iEXExchanger",
		"iPresta",
		"osCommerce",
		"osTicket",
		"ownCloud",
		"papaya CMS",
		"phpAlbum",
		"phpBB",
		"phpCMS",
		"phpDocumentor",
		"phpMyAdmin",
		"phpPgAdmin",
		"phpRS",
		"phpSQLiteCMS",
		"phpwind",
		"pinoox",
		"punBB",
		"uKnowva",
		"vBulletin",
		"vibecommerce",
		"wpBakery",
		"wpCache",
	}
}

func NodeSoftwareList() []string {
	return []string{
		"AdonisJS",
		"ApostropheCMS",
		"AquilaCMS",
		"Bubble",
		"Catberry.js",
		"Drubbit",
		"Duel",
		"Easy Orders",
		"Etherpad",
		"Express",
		"Fleksa",
		"Front-Commerce",
		"Ghost",
		"Hexo",
		"Instapage",
		"Karma",
		"Kibana",
		"Koa",
		"Marko",
		"Medium",
		"Meteor",
		"MyWebsite Now",
		"Next.js",
		"NodeBB",
		"Nuxt.js",
		"PencilBlue",
		"Phoenix",
		"Retype",
		"Sapper",
		"Socket.io",
		"Storeino",
		"SvelteKit",
		"T1 Paginas",
		"UmiJs",
		"Vnda",
		"Weblium",
		"Wiki.js",
		"Wuilt",
		"actionhero.js",
		"eDokan",
		"enduro.js",
		"total.js",
	}
}
