package report

import (
	"io"
	"strconv"
	"time"
)

const (
	defaultMaxInstances     = 50
	defaultMaxEvidenceBytes = 2048
)

// resolveLimit maps the option contract onto the renderers, where 0 means
// unlimited: zero takes the default, negative means unlimited.
func resolveLimit(v, fallback int) int {
	switch {
	case v == 0:
		return fallback
	case v < 0:
		return 0
	default:
		return v
	}
}

func pdfScopeLine(opts ReportOptions, s Summary) string {
	subject := "Workspace " + strconv.FormatUint(uint64(opts.WorkspaceID), 10)
	switch {
	case opts.ScanID != 0:
		subject = "Scan " + strconv.FormatUint(uint64(opts.ScanID), 10)
	case opts.TaskID != 0:
		subject = "Task " + strconv.FormatUint(uint64(opts.TaskID), 10)
	}

	return subject + ", covering " + strconv.Itoa(s.UniqueAffectedEndpoints) + " affected " +
		plural(s.UniqueAffectedEndpoints, "endpoint", "endpoints") + "."
}

func generatePDFReport(options ReportOptions, w io.Writer) error {
	if options.GeneratedAt.IsZero() {
		options.GeneratedAt = time.Now()
	}
	maxInstances := resolveLimit(options.MaxInstances, defaultMaxInstances)
	maxEvidenceBytes := resolveLimit(options.MaxEvidenceBytes, defaultMaxEvidenceBytes)

	reportIssues := processIssues(options.Issues, options.MaxRequestSize)
	summary := generateSummary(reportIssues)
	findings := buildPDFFindings(groupIssuesByType(reportIssues), maxInstances)

	doc, err := newPDFDoc(options)
	if err != nil {
		return err
	}

	scope := pdfScopeLine(options, summary)

	doc.coverPage(summary, scope)
	doc.executiveSummary(summary, scope)
	doc.severityDefinitions()

	tocPages := doc.reserveTOC(len(findings))

	doc.startBody()
	entries := doc.renderFindings(findings, maxEvidenceBytes)
	doc.appendix(options, maxInstances, maxEvidenceBytes)

	doc.writeTOC(tocPages, entries)

	if err := doc.finish(); err != nil {
		return err
	}
	return doc.pdf.Output(w)
}

func (d *pdfDoc) appendix(opts ReportOptions, maxInstances, maxEvidenceBytes int) {
	d.pdf.AddPage()
	d.currentFinding = "Appendix A — About this report"
	d.h1("Appendix A — About this report")

	d.body("This document was generated by sukyan from the findings recorded during automated " +
		"security testing. Findings are grouped by issue type; every instance recorded against a " +
		"type is listed beneath it with the request and response that produced it.")

	d.pdf.Ln(1)
	d.label("Report parameters")
	d.pdf.SetFont(fontSans, "", sizeCaption)
	d.setInk(inkMuted)

	rows := [][2]string{
		{"Generated", opts.GeneratedAt.Format("2006-01-02 15:04:05 MST")},
		{"Instances per finding", limitLabel(maxInstances)},
		{"Evidence budget per body", limitLabel(maxEvidenceBytes) + " bytes"},
	}
	for _, row := range rows {
		d.pdf.CellFormat(56, 4.6, row[0], "", 0, "L", false, 0, "")
		d.pdf.CellFormat(contentWidth-56, 4.6, row[1], "", 1, "L", false, 0, "")
	}

	d.setInk(inkBody)
	d.pdf.Ln(3)
	d.muted("Where evidence was truncated or instances were omitted, the document says so at the " +
		"point it happened. For the complete unabridged data, generate the JSON report over the " +
		"same scope.")
}

func limitLabel(v int) string {
	if v <= 0 {
		return "unlimited"
	}
	return strconv.Itoa(v)
}
