package http_utils

import (
	"strings"

	"github.com/pyneda/sukyan/db"
)

type WAFProvider string

const (
	WAFCloudflare  WAFProvider = "cloudflare"
	WAFAkamai      WAFProvider = "akamai"
	WAFCloudFront  WAFProvider = "cloudfront"
	WAFImperva     WAFProvider = "imperva"
	WAFFastly      WAFProvider = "fastly"
	WAFSucuri      WAFProvider = "sucuri"
	WAFDataDome    WAFProvider = "datadome"
	WAFModSecurity WAFProvider = "modsecurity"
	WAFAWSShield   WAFProvider = "aws_shield"
	WAFUnknown     WAFProvider = "unknown"
)

type WAFIdentification struct {
	Detected  bool
	Provider  WAFProvider
	Details   []string
	IsBlocked bool
	BlockType string // "challenge", "block", "rate_limit", "captcha"
}

type headerSignature struct {
	header string
	value  string // empty means any value matches
}

var wafHeaderSignatures = map[WAFProvider][]headerSignature{
	WAFCloudflare: {
		{header: "cf-ray", value: ""},
		{header: "server", value: "cloudflare"},
	},
	WAFAkamai: {
		{header: "x-akamai-transformed", value: ""},
		{header: "akamai-cache-status", value: ""},
		{header: "x-akamai-request-id", value: ""},
	},
	WAFCloudFront: {
		{header: "x-amz-cf-id", value: ""},
		{header: "x-amz-cf-pop", value: ""},
	},
	WAFImperva: {
		{header: "x-iinfo", value: ""},
		{header: "x-cdn", value: "incapsula"},
	},
	WAFFastly: {
		{header: "x-served-by", value: "cache-"},
		{header: "x-timer", value: ""},
		{header: "fastly-debug-digest", value: ""},
	},
	WAFSucuri: {
		{header: "x-sucuri-id", value: ""},
		{header: "x-sucuri-cache", value: ""},
		{header: "server", value: "sucuri"},
	},
	WAFDataDome: {
		{header: "x-datadome", value: ""},
		{header: "server", value: "datadome"},
	},
}

var wafServerPatterns = map[WAFProvider][]string{
	WAFCloudflare:  {"cloudflare"},
	WAFAkamai:      {"akamaighost", "akamai"},
	WAFCloudFront:  {"cloudfront"},
	WAFImperva:     {"imperva", "incapsula"},
	WAFSucuri:      {"sucuri/cloudproxy", "sucuri"},
	WAFDataDome:    {"datadome"},
	WAFModSecurity: {"mod_security"},
}

// IdentifyWAF detects which WAF/CDN protects a target based on response headers.
func IdentifyWAF(headers map[string][]string) WAFIdentification {
	result := WAFIdentification{}

	normalizedHeaders := make(map[string][]string)
	for k, v := range headers {
		normalizedHeaders[strings.ToLower(k)] = v
	}

	for provider, signatures := range wafHeaderSignatures {
		for _, sig := range signatures {
			values, exists := normalizedHeaders[sig.header]
			if !exists {
				continue
			}
			if sig.value == "" {
				result.Detected = true
				result.Provider = provider
				result.Details = append(result.Details, sig.header+": "+strings.Join(values, ", "))
				return result
			}
			for _, v := range values {
				if strings.Contains(strings.ToLower(v), sig.value) {
					result.Detected = true
					result.Provider = provider
					result.Details = append(result.Details, sig.header+": "+v)
					return result
				}
			}
		}
	}

	// Check Server header patterns
	if serverValues, exists := normalizedHeaders["server"]; exists {
		serverStr := strings.ToLower(strings.Join(serverValues, " "))
		for provider, patterns := range wafServerPatterns {
			for _, pattern := range patterns {
				if strings.Contains(serverStr, pattern) {
					result.Detected = true
					result.Provider = provider
					result.Details = append(result.Details, "server: "+serverStr)
					return result
				}
			}
		}
	}

	// Check Via header for CloudFront
	if viaValues, exists := normalizedHeaders["via"]; exists {
		viaStr := strings.ToLower(strings.Join(viaValues, " "))
		if strings.Contains(viaStr, "cloudfront") {
			result.Detected = true
			result.Provider = WAFCloudFront
			result.Details = append(result.Details, "via: "+strings.Join(viaValues, ", "))
			return result
		}
	}

	return result
}

// IdentifyWAFFromHistory detects WAF from a stored history item.
func IdentifyWAFFromHistory(history *db.History) WAFIdentification {
	headers, err := history.GetResponseHeadersAsMap()
	if err != nil {
		return WAFIdentification{}
	}
	return IdentifyWAF(headers)
}

type blockSignature struct {
	bodyPatterns  []string
	titlePattern  string
	statusCodes   []int
}

var wafBlockSignatures = map[WAFProvider]blockSignature{
	WAFCloudflare: {
		bodyPatterns: []string{
			"cf-error-details",
			"Attention Required! | Cloudflare",
			"Cloudflare Ray ID",
			"Why have I been blocked",
			"challenge-platform",
			"cf-challenge",
			"<title>Just a moment...</title>",
			"cf-turnstile",
			"You are being rate limited",
			"Error 1005",
			"Error 1006",
			"Error 1015",
			"Error 1020",
		},
		statusCodes: []int{403, 429, 503},
	},
	WAFCloudFront: {
		bodyPatterns: []string{
			"Generated by cloudfront (CloudFront)",
			"Request blocked",
			"The request could not be satisfied",
			"ERROR: The request could not be satisfied",
		},
		titlePattern: "ERROR: The request could not be satisfied",
		statusCodes:  []int{403, 502, 503},
	},
	WAFAkamai: {
		bodyPatterns: []string{
			"Access Denied",
			"AkamaiGHost",
			"Reference&#32;&#35;",
			"akamai.com/apps/abuse-feedback",
		},
		statusCodes: []int{403},
	},
	WAFImperva: {
		bodyPatterns: []string{
			"incapsula",
			"Incapsula incident ID",
			"_Incapsula_Resource",
			"Request unsuccessful. Incapsula incident",
		},
		statusCodes: []int{403},
	},
	WAFSucuri: {
		bodyPatterns: []string{
			"Sucuri WebSite Firewall",
			"Access Denied - Sucuri",
			"sucuri.net/privacy-policy",
			"cloudproxy@sucuri.net",
		},
		statusCodes: []int{403},
	},
	WAFDataDome: {
		bodyPatterns: []string{
			"DataDome",
			"datadome.co/",
		},
		statusCodes: []int{403},
	},
	WAFModSecurity: {
		bodyPatterns: []string{
			"ModSecurity",
			"Mod_Security",
			"This error was generated by Mod_Security",
			"Not Acceptable!",
			"NOYB",
		},
		statusCodes: []int{403, 406},
	},
}

// Generic block patterns that don't identify a specific WAF
var genericBlockPatterns = []string{
	"Request blocked",
	"Access Denied",
	"Forbidden",
	"Web Application Firewall",
	"Your request has been blocked",
	"This request has been blocked by the security rules",
	"security violation",
}

// IsWAFBlock checks if a response is a WAF block page.
// It returns the identification with IsBlocked and BlockType set.
func IsWAFBlock(history *db.History) WAFIdentification {
	waf := IdentifyWAFFromHistory(history)

	body, _ := history.ResponseBody()
	bodyStr := string(body)
	bodyLower := strings.ToLower(bodyStr)

	// If we know the WAF, check its specific block signatures
	if waf.Detected {
		if sig, exists := wafBlockSignatures[waf.Provider]; exists {
			statusMatch := false
			for _, code := range sig.statusCodes {
				if history.StatusCode == code {
					statusMatch = true
					break
				}
			}

			for _, pattern := range sig.bodyPatterns {
				if strings.Contains(bodyLower, strings.ToLower(pattern)) {
					waf.IsBlocked = true
					if history.StatusCode == 429 {
						waf.BlockType = "rate_limit"
					} else if strings.Contains(bodyLower, "challenge") || strings.Contains(bodyLower, "captcha") || strings.Contains(bodyLower, "turnstile") || strings.Contains(bodyLower, "just a moment") {
						waf.BlockType = "challenge"
					} else {
						waf.BlockType = "block"
					}
					waf.Details = append(waf.Details, "Block pattern: "+pattern)
					return waf
				}
			}

			// Status code match without body pattern — might still be a block
			// but lower confidence, don't mark as blocked without body evidence
			_ = statusMatch
		}
	}

	// If no WAF identified yet, check all block signatures
	if !waf.IsBlocked {
		for provider, sig := range wafBlockSignatures {
			for _, pattern := range sig.bodyPatterns {
				if strings.Contains(bodyLower, strings.ToLower(pattern)) {
					statusMatch := false
					for _, code := range sig.statusCodes {
						if history.StatusCode == code {
							statusMatch = true
							break
						}
					}
					if statusMatch {
						waf.Detected = true
						waf.Provider = provider
						waf.IsBlocked = true
						waf.BlockType = "block"
						waf.Details = append(waf.Details, "Block pattern: "+pattern)
						return waf
					}
				}
			}
		}
	}

	// Check generic block patterns on 403/429/503 HTML responses only
	// JSON/API responses with "Forbidden" are application-level errors, not WAF blocks
	isHTML := strings.Contains(strings.ToLower(history.ResponseContentType), "text/html")
	if !waf.IsBlocked && isHTML && (history.StatusCode == 403 || history.StatusCode == 429 || history.StatusCode == 503) {
		for _, pattern := range genericBlockPatterns {
			if strings.Contains(bodyLower, strings.ToLower(pattern)) {
				waf.IsBlocked = true
				waf.BlockType = "block"
				if !waf.Detected {
					waf.Provider = WAFUnknown
				}
				waf.Details = append(waf.Details, "Generic block pattern: "+pattern)
				return waf
			}
		}
	}

	return waf
}
