package http_utils

import (
	"testing"

	"github.com/pyneda/sukyan/db"
	"github.com/stretchr/testify/assert"
)

func TestIdentifyWAF(t *testing.T) {
	tests := []struct {
		name     string
		headers  map[string][]string
		expected WAFProvider
		detected bool
	}{
		{
			name: "Cloudflare via cf-ray",
			headers: map[string][]string{
				"Cf-Ray": {"9ee057c769993c2d-CEB"},
				"Server": {"cloudflare"},
			},
			expected: WAFCloudflare,
			detected: true,
		},
		{
			name: "CloudFront via X-Amz-Cf-Id",
			headers: map[string][]string{
				"X-Amz-Cf-Id":  {"uWyEAb8A343i1aAV2KCn81PYVpKAiJsB"},
				"X-Amz-Cf-Pop": {"MNL52-P1"},
				"Server":       {"Server"},
			},
			expected: WAFCloudFront,
			detected: true,
		},
		{
			name: "CloudFront via Via header",
			headers: map[string][]string{
				"Via":    {"1.1 c16f288d4c4250717fab8cb387b33448.cloudfront.net (CloudFront)"},
				"Server": {"Server"},
			},
			expected: WAFCloudFront,
			detected: true,
		},
		{
			name: "Fastly via x-served-by",
			headers: map[string][]string{
				"X-Served-By": {"cache-sjc1000108-SJC, cache-sjc1000143-SJC"},
				"X-Timer":     {"S1776480459.127282,VS0,VE0"},
				"Server":      {"Artisanal bits"},
			},
			expected: WAFFastly,
			detected: true,
		},
		{
			name: "Sucuri via server header",
			headers: map[string][]string{
				"Server":        {"Sucuri/Cloudproxy"},
				"X-Sucuri-Id":   {"18012"},
				"X-Sucuri-Cache": {"HIT"},
			},
			expected: WAFSucuri,
			detected: true,
		},
		{
			name: "DataDome via server header",
			headers: map[string][]string{
				"Server": {"DataDome"},
			},
			expected: WAFDataDome,
			detected: true,
		},
		{
			name: "Imperva via x-cdn header",
			headers: map[string][]string{
				"X-CDN": {"Incapsula"},
			},
			expected: WAFImperva,
			detected: true,
		},
		{
			name:     "No WAF detected",
			headers: map[string][]string{
				"Server":       {"nginx/1.24.0"},
				"Content-Type": {"text/html"},
			},
			expected: "",
			detected: false,
		},
		{
			name:     "Empty headers",
			headers:  map[string][]string{},
			expected: "",
			detected: false,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			result := IdentifyWAF(tt.headers)
			assert.Equal(t, tt.detected, result.Detected)
			if tt.detected {
				assert.Equal(t, tt.expected, result.Provider)
				assert.NotEmpty(t, result.Details)
			}
		})
	}
}

func TestIdentifyWAF_CaseInsensitive(t *testing.T) {
	// Headers can come in any case
	result := IdentifyWAF(map[string][]string{
		"CF-RAY": {"abc123"},
		"SERVER": {"CLOUDFLARE"},
	})
	assert.True(t, result.Detected)
	assert.Equal(t, WAFCloudflare, result.Provider)
}

func TestIsWAFBlock_CloudflareBlockBody(t *testing.T) {
	// Real Cloudflare block page body excerpt
	body := `<!DOCTYPE html><html><head><title>Attention Required! | Cloudflare</title></head>
	<body><div class="cf-error-details-wrapper"><h2>Why have I been blocked?</h2>
	<p>This website is using a security service to protect itself from online attacks.</p>
	<p>Cloudflare Ray ID: 9ee0582ba9d381a4</p></div></body></html>`

	headers := map[string][]string{
		"Server": {"cloudflare"},
		"Cf-Ray": {"9ee0582ba9d381a4"},
	}

	history := &db.History{
		StatusCode:          403,
		RawResponse:         []byte("HTTP/1.1 403 Forbidden\r\nServer: cloudflare\r\nCf-Ray: 9ee0582ba9d381a4\r\n\r\n" + body),
		ResponseContentType: "text/html",
		ResponseBodySize:    len(body),
	}
	// Manually set the headers for the test
	_ = headers

	result := IsWAFBlock(history)
	assert.True(t, result.Detected)
	assert.Equal(t, WAFCloudflare, result.Provider)
	assert.True(t, result.IsBlocked)
	assert.Equal(t, "block", result.BlockType)
}

func TestIsWAFBlock_CloudflareChallengeBody(t *testing.T) {
	body := `<!DOCTYPE html><html><head><title>Just a moment...</title></head>
	<body><div id="challenge-platform"><div id="cf-challenge"></div></div></body></html>`

	history := &db.History{
		StatusCode:          503,
		RawResponse:         []byte("HTTP/1.1 503 Service Unavailable\r\nServer: cloudflare\r\nCf-Ray: abc123\r\n\r\n" + body),
		ResponseContentType: "text/html",
		ResponseBodySize:    len(body),
	}

	result := IsWAFBlock(history)
	assert.True(t, result.Detected)
	assert.Equal(t, WAFCloudflare, result.Provider)
	assert.True(t, result.IsBlocked)
	assert.Equal(t, "challenge", result.BlockType)
}

func TestIsWAFBlock_CloudFrontBlock(t *testing.T) {
	body := `<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
	<HTML><HEAD><TITLE>ERROR: The request could not be satisfied</TITLE></HEAD>
	<BODY><H1>403 ERROR</H1><H2>The request could not be satisfied.</H2>
	Request blocked. Generated by cloudfront (CloudFront)
	Request ID: n_EeRY6DFu5wjcHH6p9Ih8ZccGwVKM8ixKJ5vBs4NGLwqMqubwWdhg==</BODY></HTML>`

	history := &db.History{
		StatusCode:          403,
		RawResponse:         []byte("HTTP/1.1 403 Forbidden\r\nServer: CloudFront\r\nX-Amz-Cf-Id: abc\r\nVia: 1.1 xyz.cloudfront.net (CloudFront)\r\n\r\n" + body),
		ResponseContentType: "text/html",
		ResponseBodySize:    len(body),
	}

	result := IsWAFBlock(history)
	assert.True(t, result.Detected)
	assert.Equal(t, WAFCloudFront, result.Provider)
	assert.True(t, result.IsBlocked)
}

func TestIsWAFBlock_NormalResponse(t *testing.T) {
	body := `<!DOCTYPE html><html><head><title>Welcome</title></head>
	<body><h1>Hello World</h1></body></html>`

	history := &db.History{
		StatusCode:          200,
		RawResponse:         []byte("HTTP/1.1 200 OK\r\nServer: nginx\r\n\r\n" + body),
		ResponseContentType: "text/html",
		ResponseBodySize:    len(body),
	}

	result := IsWAFBlock(history)
	assert.False(t, result.IsBlocked)
}

func TestIsWAFBlock_CloudflareNonBlock403(t *testing.T) {
	// A 403 from Cloudflare that is NOT a block (app-level 403)
	body := `{"error": "Forbidden", "message": "You do not have access to this resource"}`

	history := &db.History{
		StatusCode:          403,
		RawResponse:         []byte("HTTP/1.1 403 Forbidden\r\nServer: cloudflare\r\nCf-Ray: abc123\r\nContent-Type: application/json\r\n\r\n" + body),
		ResponseContentType: "application/json",
		ResponseBodySize:    len(body),
	}

	result := IsWAFBlock(history)
	// WAF is detected (Cloudflare) but the response is NOT a WAF block
	assert.True(t, result.Detected)
	assert.Equal(t, WAFCloudflare, result.Provider)
	assert.False(t, result.IsBlocked)
}

func TestIsWAFBlock_RateLimit(t *testing.T) {
	body := `<html><body>You are being rate limited</body></html>`

	history := &db.History{
		StatusCode:          429,
		RawResponse:         []byte("HTTP/1.1 429 Too Many Requests\r\nServer: cloudflare\r\nCf-Ray: xyz\r\n\r\n" + body),
		ResponseContentType: "text/html",
		ResponseBodySize:    len(body),
	}

	result := IsWAFBlock(history)
	assert.True(t, result.IsBlocked)
	assert.Equal(t, "rate_limit", result.BlockType)
}
