definitions:
  api.HistorySummary:
    properties:
      depth:
        type: integer
      id:
        type: integer
      method:
        type: string
      parameters_count:
        type: integer
      status_code:
        type: integer
      url:
        type: string
    type: object
  api.PassiveScanInput:
    properties:
      items:
        items:
          type: integer
        type: array
    required:
    - items
    type: object
info:
  contact: {}
paths:
  /api/history/{id}/children:
    get:
      consumes:
      - application/json
      description: Get all the other history items that have the same depth or more
        than the provided history ID and that start with the same URL
      parameters:
      - description: History ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/api.HistorySummary'
            type: array
        "400":
          description: Bad Request
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
      summary: Get children history
      tags:
      - History
  /api/history/root-nodes:
    get:
      consumes:
      - application/json
      description: Get all the root history items
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/api.HistorySummary'
            type: array
        "400":
          description: Bad Request
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
      summary: Gets all root history nodes
      tags:
      - History
  /api/scan/active:
    post:
      consumes:
      - application/json
      description: Receives a list of items and schedules them for active scanning
      parameters:
      - description: List of items
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/api.PassiveScanInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Submit items for active scanning
      tags:
      - Scan
  /api/scan/passive:
    post:
      consumes:
      - application/json
      description: Receives a list of items and schedules them for passive scanning
      parameters:
      - description: List of items
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/api.PassiveScanInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Submit items for passive scanning
      tags:
      - Scan
  /history:
    get:
      description: Get history with optional pagination and filtering by status codes,
        HTTP methods, and sources
      parameters:
      - default: 50
        description: Size of each page
        in: query
        name: page_size
        type: integer
      - default: 1
        description: Page number
        in: query
        name: page
        type: integer
      - description: Comma-separated list of status codes to filter by
        in: query
        name: status
        type: string
      - description: Comma-separated list of HTTP methods to filter by
        in: query
        name: methods
        type: string
      - description: Comma-separated list of sources to filter by
        in: query
        name: sources
        type: string
      produces:
      - application/json
      responses: {}
      summary: Get history
      tags:
      - History
  /interactions:
    get:
      description: Get interactions with optional pagination and protocols filter
      parameters:
      - default: 50
        description: Size of each page
        in: query
        name: page_size
        type: integer
      - default: 1
        description: Page number
        in: query
        name: page
        type: integer
      - description: Comma-separated list of protocols to filter by
        in: query
        name: protocols
        type: string
      produces:
      - application/json
      responses: {}
      summary: Get interactions
      tags:
      - Interactions
  /tasks/:
    get:
      consumes:
      - application/json
      description: Allows to filter and search task jobs
      parameters:
      - description: Task ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses: {}
      summary: Search Task Jobs
      tags:
      - tasks
swagger: "2.0"
